(window['webpackJsonp'] = window['webpackJsonp'] || []).push([
  [25],
  {
    'F+kV': function (e, t, a) {
      'use strict';
      a.r(t);
      var l = a('cDcd'),
        n = a.n(l),
        c = a('dEAq'),
        i = (a('1R9V'), a('ZpkN'));
      a('TN5+'), a('HVN5'), a('tP8H'), a('UpFc');
      t['default'] = function () {
        return n.a.createElement(
          n.a.Fragment,
          null,
          n.a.createElement(
            'div',
            { className: 'markdown' },
            n.a.createElement(
              'h2',
              { id: '\u4f7f\u7528\u6307\u5357' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u4f7f\u7528\u6307\u5357', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u4f7f\u7528\u6307\u5357',
            ),
            n.a.createElement(
              'h3',
              { id: '\u5b89\u88c5' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u5b89\u88c5', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u5b89\u88c5',
            ),
            n.a.createElement(i['a'], { code: 'yarn add weui-react-v2\n', lang: 'bash' }),
            n.a.createElement(
              'h3',
              { id: '\u91cd\u8981\u63d0\u9192' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u91cd\u8981\u63d0\u9192', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u91cd\u8981\u63d0\u9192',
            ),
            n.a.createElement(
              'blockquote',
              null,
              n.a.createElement(
                'p',
                null,
                '\u76ee\u524d\u7531\u4e8e',
                n.a.createElement('code', null, 'react-spring@9.0.0-rc.2'),
                '\u5b58\u5728\u5faa\u73af\u4f9d\u8d56\u95ee\u9898\uff0c\u4f1a\u5728\u6253\u5305\u751f\u4ea7\u4ee3\u7801\u65f6\u9020\u6210\u9519\u8bef\u3002\u6b64\u95ee\u9898\u5c06\u5728',
                n.a.createElement('code', null, 'react-spring@9.0.0-rc.4'),
                '\u540e\u4fee\u590d\u3002\u5728\u6b64\u4e4b\u524d\uff0c\u8bf7\u5c06',
                n.a.createElement('code', null, 'react-spring'),
                '\u5e93\u589e\u52a0\u5230',
                n.a.createElement('code', null, 'externals'),
                '\u91cc\u6253\u5305\u6392\u9664',
              ),
            ),
            n.a.createElement(
              'h3',
              { id: '\u4f7f\u7528' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u4f7f\u7528', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u4f7f\u7528',
            ),
            n.a.createElement(
              'p',
              null,
              n.a.createElement('code', null, 'weui-react-v2'),
              '\u65e0\u7f1d\u8d34\u5408',
              n.a.createElement('code', null, 'umi'),
              '\u751f\u6001\uff0c\u5728',
              n.a.createElement('code', null, 'umi'),
              '\u9879\u76ee\u4e2d\u76f4\u63a5\u8fd0\u884c\u5c31\u652f\u6301\u6811\u6447\uff0c\u4e0d\u7528\u663e\u793a\u5f15\u5165\u6837\u5f0f\uff0c\u975e\u5e38\u65b9\u4fbf\u3002\u800c\u4e14\u53ef\u57fa\u4e8e',
              n.a.createElement('code', null, 'umi'),
              '\u7684\u4e3b\u9898\u914d\u7f6e\u5b9a\u4e49\u4e3b\u9898\u6837\u5f0f.',
            ),
            n.a.createElement(
              'blockquote',
              null,
              n.a.createElement(
                'p',
                null,
                'Tips: \u8bf7\u6ce8\u610f\uff0c\u6b64\u5e93\u7ec4\u4ef6\u57fa\u4e8e 750px \u8bbe\u8ba1\u7a3f, \u8bf7\u4f7f\u7528',
                n.a.createElement('code', null, 'post-css'),
                '\u7b49\u540e\u5904\u7406\u8d77\uff0c\u5c06\u6b64\u5e93\u7684',
                n.a.createElement('code', null, 'px'),
                '\u8f6c\u6362\u4e3a',
                n.a.createElement('code', null, 'rem'),
                '\u6216',
                n.a.createElement('code', null, 'vw'),
                '\uff0c \u5177\u4f53\u770b\u4f60\u81ea\u5df1\u7684\u9002\u914d\u65b9\u6848.',
              ),
            ),
            n.a.createElement(
              'blockquote',
              null,
              n.a.createElement(
                'p',
                null,
                'Tips: \u9879\u76ee\u5f15\u5165\u4e86\u97f3\u6548\u6587\u4ef6\uff0c\u6240\u4ee5\u8bf7\u914d\u7f6e',
                n.a.createElement('code', null, 'file-loader'),
              ),
            ),
            n.a.createElement(i['a'], {
              code:
                "// umi\u914d\u7f6e\nimport { defineConfig } from 'umi';\nexport default defineConfig({\n  theme: {\n    '@primary-color': '#CDDC39',\n  },\n  routes: [{ path: '/', component: '@/pages/index' }],\n});\n",
              lang: 'ts',
            }),
            n.a.createElement(
              'p',
              null,
              '\u5728\u975e',
              n.a.createElement('code', null, 'umi'),
              '\u9879\u76ee\u4e2d, \u4e5f\u53ea\u9700\u8981\u914d\u7f6e',
              n.a.createElement('code', null, 'less-loader'),
              '\u7684',
              n.a.createElement('code', null, 'modifyVars'),
              '\u9009\u9879\uff0c\u4e5f\u80fd\u6362\u80a4.',
            ),
            n.a.createElement(i['a'], {
              code:
                '{\n  module: {\n    rules: [\n      test: /\\.less$/,\n      loaders: [\n        "style-loader",\n        "css-loader",\n        {\n            loader: "less-loader",\n            options: {\n              lessOptions: {\n                javascriptEnabled: true,\n                modifyVars: {\n                  "@primary-color": "#CDDC39",\n                },\n              },\n            },\n          },\n      ]\n    ]\n  }\n}\n',
              lang: 'js',
            }),
            n.a.createElement(
              'h2',
              { id: '\u8def\u7ebf\u56fe' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u8def\u7ebf\u56fe', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u8def\u7ebf\u56fe',
            ),
            n.a.createElement(
              'h3',
              { id: '\u73b0\u6709\u95ee\u9898' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u73b0\u6709\u95ee\u9898', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u73b0\u6709\u95ee\u9898',
            ),
            n.a.createElement(
              'ul',
              null,
              n.a.createElement(
                'li',
                null,
                '\u8bbe\u8ba1\u7684\u662f\u901a\u8fc7\u6811\u6447\uff0c\u53ea\u6253\u5305\u4f7f\u7528\u7684\u7ec4\u4ef6\u548c\u6837\u5f0f\u3002\u5b9e\u9645\u4e0a\u5fc5\u987b\u5728 main.ts \u91cc\u5f15\u5165\u6240\u6709\u6837\u5f0f\uff0c\u5e76\u4e14\u5199\u7a7a\u8868\u8fbe\u5f0f\u6765\u9632\u6b62\u751f\u4ea7\u6253\u5305\u6837\u5f0f\u88ab\u4f18\u5316\u6389',
              ),
            ),
            n.a.createElement(
              'h3',
              { id: '\u4ece\u9700\u6c42\u51fa\u53d1' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u4ece\u9700\u6c42\u51fa\u53d1', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u4ece\u9700\u6c42\u51fa\u53d1',
            ),
            n.a.createElement(
              'p',
              null,
              '\u76ee\u7684\u662f\u6253\u9020\u4e00\u5957\u8f7b\u5feb\u4e0a\u624b\u7684\u79fb\u52a8\u7aef\u7ec4\u4ef6\uff0c\u7ec4\u4ef6\u6837\u5f0f\u53c2\u7167',
              n.a.createElement('code', null, 'weui'),
              '\u6700\u65b0\u89c4\u8303\u3002',
            ),
            n.a.createElement(
              'ul',
              { className: ['contains-task-list'] },
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' \u8f7b\u4fbf\uff0c\u53bb\u9664\u975e\u5e38\u590d\u6742\u7684\u529f\u80fd\uff0c\u53ea\u4fdd\u7559\u7ecf\u5e38\u7528\u7684\u529f\u80fd',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' \u4f7f\u7528 umi-hd \u7684 rem \u65b9\u6848',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' \u53ef\u8986\u76d6\u7684\u4e3b\u9898\u98ce\u683c, \u7f16\u8bd1 bundle.css \u548c\u76f4\u63a5\u5f15\u5165.less \u540c\u65f6\u652f\u6301',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' \u6613\u4e8e\u4f7f\u7528\u7684 api',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' \u7ec4\u4ef6\u7684\u52a8\u6548\u6e05\u723d',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' \u652f\u6301\u6811\u6447',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' \u89e6\u6478\u53cb\u597d, \u652f\u6301\u591a\u624b\u52bf\u64cd\u4f5c',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' \u6bcf\u4e2a\u7ec4\u4ef6\u7f16\u5199\u6d4b\u8bd5\u548c\u6587\u6863',
              ),
            ),
            n.a.createElement(
              'h2',
              { id: '\u7ec4\u4ef6' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u7ec4\u4ef6', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u7ec4\u4ef6',
            ),
            n.a.createElement(
              'h3',
              { id: '\u901a\u7528' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u901a\u7528', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u901a\u7528',
            ),
            n.a.createElement(
              'ul',
              { className: ['contains-task-list'] },
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Button'),
                ' \u6309\u94ae',
              ),
            ),
            n.a.createElement(
              'h3',
              { id: '\u6570\u636e\u8f93\u5165' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u6570\u636e\u8f93\u5165', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u6570\u636e\u8f93\u5165',
            ),
            n.a.createElement(
              'blockquote',
              null,
              n.a.createElement(
                'p',
                null,
                '\u8868\u5355\u7ec4\u4ef6\u57fa\u4e8e',
                n.a.createElement('code', null, 'rc-form'),
              ),
            ),
            n.a.createElement(
              'ul',
              { className: ['contains-task-list'] },
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Form'),
                ' \u8868\u5355\u7ec4\u4ef6\uff0c\u53ef\u6709\u53ef\u65e0\u3002\u63d0\u4f9b\u5c01\u88c5',
                n.a.createElement('code', null, 'label'),
                '\u5bbd\u5ea6\uff0c\u7b49\u901a\u7528\u6837\u5f0f\u548c\u9a8c\u8bc1\uff0conSubmit \u7b49\u529f\u80fd\u3002',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'FormItem'),
                ' \u53ef\u4ee5\u5305\u88f9\u8868\u5355\u7ec4\u4ef6',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Input'),
                ' \u8f93\u5165\u6846\uff0c \u652f\u6301\u591a\u79cd\u7c7b\u578b\uff0c\u6bd4\u5982\u624b\u673a\u53f7\uff0c\u8eab\u4efd\u8bc1\uff0c\u94f6\u884c\u5361\u7684\u683c\u5f0f\u5316',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'TextArea'),
                ' \u6587\u672c\u57df',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Checkbox'),
                ' \u590d\u9009\u6846',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Switch'),
                ' \u5207\u6362\u5f00\u5173',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Picker'),
                ' \u9009\u62e9\u5668',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'DatePicker'),
                ' \u65e5\u671f\u9009\u62e9',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'ImagePicker'),
                ' \u56fe\u7247\u9009\u62e9',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'SearchBar'),
                ' \u641c\u7d22\u680f',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Rate'),
                '\u8bc4\u7ea7',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'AmountKeyboard'),
                ' \u91d1\u989d\u952e\u76d8',
              ),
            ),
            n.a.createElement(
              'h3',
              { id: '\u5e03\u5c40' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u5e03\u5c40', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u5e03\u5c40',
            ),
            n.a.createElement(
              'ul',
              { className: ['contains-task-list'] },
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Flex'),
                ' \u5f39\u6027\u5e03\u5c40',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'WingBlank'),
                ' \u4e24\u7ffc\u7559\u767d',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'WhiteSpace'),
                ' \u4e0a\u4e0b\u7559\u767d',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'SafeArea'),
                ' \u5b89\u5168\u7a7a\u95f4',
              ),
            ),
            n.a.createElement(
              'h3',
              { id: '\u5bfc\u822a' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u5bfc\u822a', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u5bfc\u822a',
            ),
            n.a.createElement(
              'ul',
              { className: ['contains-task-list'] },
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Tabs'),
                ' , \u6ed1\u52a8\u57fa\u4e8e',
                n.a.createElement('code', null, 'swiper'),
              ),
            ),
            n.a.createElement(
              'h3',
              { id: '\u6570\u636e\u5c55\u793a' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u6570\u636e\u5c55\u793a', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u6570\u636e\u5c55\u793a',
            ),
            n.a.createElement(
              'ul',
              { className: ['contains-task-list'] },
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'List'),
                ' \u5217\u8868',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Panel'),
                ' \u9762\u677f',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Grid'),
                ' \u4e5d\u5bab\u683c',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Preview'),
                ' \u8868\u5355\u9884\u89c8',
              ),
            ),
            n.a.createElement(
              'h3',
              { id: '\u64cd\u4f5c\u53cd\u9988' },
              n.a.createElement(
                c['AnchorLink'],
                { to: '#\u64cd\u4f5c\u53cd\u9988', 'aria-hidden': 'true', tabIndex: -1 },
                n.a.createElement('span', { className: ['icon', 'icon-link'] }),
              ),
              '\u64cd\u4f5c\u53cd\u9988',
            ),
            n.a.createElement(
              'ul',
              { className: ['contains-task-list'] },
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'ActionSheet'),
                ' \u5f39\u51fa\u5f0f\u83dc\u5355',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Model'),
                ' \u6a21\u6001\u5bf9\u8bdd\u6846',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'HalfScreenDialog'),
                ' \u534a\u5c4f\u5bf9\u8bdd\u6846',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Toast'),
                ' \u8f7b\u63d0\u793a',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Toptips'),
                ' \u9876\u90e8\u63d0\u793a',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Spin'),
                ' \u52a0\u8f7d\u4e2d',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Loading'),
                ' \u52a0\u8f7d\u4e2d',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'loadmore'),
                ' \u52a0\u8f7d\u66f4\u591a',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Skeleton'),
                ' \u9aa8\u67b6\u5c4f',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'SwiperAction'),
                ' \u6ed1\u52a8\u64cd\u4f5c',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Swiper'),
                ' \u8f6e\u64ad',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'PullRefresh'),
                ' \u4e0a\u6ed1\u52a0\u8f7d\uff0c\u4e0b\u62c9\u5237\u65b0',
              ),
              n.a.createElement(
                'li',
                { className: ['task-list-item'] },
                n.a.createElement('input', { type: 'checkbox', defaultChecked: !0, disabled: !0 }),
                ' ',
                n.a.createElement('code', null, 'Gallery'),
                ' \u56fe\u7247\u67e5\u770b\u5668',
              ),
            ),
          ),
        );
      };
    },
    HVN5: function (e, t, a) {
      'use strict';
      a('0Owb'), a('cDcd'), a('mlvz');
    },
    OGKa: function (e, t, a) {},
    'TN5+': function (e, t, a) {
      'use strict';
      a('0Owb'), a('cDcd'), a('kERV');
    },
    UpFc: function (e, t, a) {
      'use strict';
      var l = a('cDcd'),
        n = a.n(l),
        c = a('dEAq'),
        i = {
          'zh-CN': {
            name: '\u5c5e\u6027\u540d',
            description: '\u63cf\u8ff0',
            type: '\u7c7b\u578b',
            default: '\u9ed8\u8ba4\u503c',
            required: '(\u5fc5\u9009)',
          },
          'en-US': {
            name: 'Name',
            description: 'Description',
            type: 'Type',
            default: 'Default',
            required: '(required)',
          },
        };
      t['a'] = (e) => {
        var t = e.identifier,
          a = e.export,
          m = Object(c['useApiData'])(t),
          r = Object(l['useContext'])(c['context']),
          s = r.locale,
          d = i[s] || i['en-US'];
        return n.a.createElement(
          n.a.Fragment,
          null,
          m &&
            n.a.createElement(
              'table',
              { style: { marginTop: 24 } },
              n.a.createElement(
                'thead',
                null,
                n.a.createElement(
                  'tr',
                  null,
                  n.a.createElement('th', null, d.name),
                  n.a.createElement('th', null, d.description),
                  n.a.createElement('th', null, d.type),
                  n.a.createElement('th', null, d.default),
                ),
              ),
              n.a.createElement(
                'tbody',
                null,
                m[a].map((e) =>
                  n.a.createElement(
                    'tr',
                    { key: e.identifier },
                    n.a.createElement('td', null, e.identifier),
                    n.a.createElement('td', null, e.description || '--'),
                    n.a.createElement('td', null, n.a.createElement('code', null, e.type)),
                    n.a.createElement(
                      'td',
                      null,
                      n.a.createElement('code', null, e.default || (e.required && d.required) || '--'),
                    ),
                  ),
                ),
              ),
            ),
        );
      };
    },
    kERV: function (e, t, a) {},
    mlvz: function (e, t, a) {},
    tP8H: function (e, t, a) {
      'use strict';
      a('tJVT'), a('cDcd'), a('OGKa');
    },
  },
]);
